# Generated by Django 4.1.4 on 2022-12-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveDiabetesEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.CharField(max_length=10)),
                ('glucose', models.CharField(max_length=10)),
                ('bp', models.CharField(max_length=10)),
                ('st', models.CharField(max_length=10)),
                ('insulin', models.CharField(max_length=10)),
                ('bmi', models.CharField(max_length=10)),
                ('dpf', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SaveHeartEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('cp', models.CharField(max_length=10)),
                ('trestbps', models.CharField(max_length=10)),
                ('chol', models.CharField(max_length=10)),
                ('fbs', models.CharField(max_length=10)),
                ('restecg', models.CharField(max_length=10)),
                ('thalach', models.CharField(max_length=10)),
                ('exang', models.CharField(max_length=10)),
                ('oldpeak', models.CharField(max_length=10)),
                ('slope', models.CharField(max_length=10)),
                ('ca', models.CharField(max_length=10)),
                ('thal', models.CharField(max_length=10)),
            ],
        ),
    ]
