# Generated by Django 4.1.4 on 2023-01-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveStrokeEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('hypertension', models.CharField(max_length=10)),
                ('heart_disease', models.CharField(max_length=10)),
                ('avg_glucose_level', models.CharField(max_length=10)),
                ('bmi', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('married', models.CharField(max_length=10)),
                ('work_type', models.CharField(max_length=10)),
                ('residence_type', models.CharField(max_length=10)),
                ('smoking_status', models.CharField(max_length=10)),
            ],
        ),
    ]
