# Generated by Django 4.1.4 on 2023-01-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0002_savestrokeenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveLungCancerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('smoking', models.CharField(max_length=10)),
                ('yellow_fingers', models.CharField(max_length=10)),
                ('anxiety', models.CharField(max_length=10)),
                ('peer_pressure', models.CharField(max_length=10)),
                ('chronic_disease', models.CharField(max_length=10)),
                ('fatigue', models.CharField(max_length=10)),
                ('allergy', models.CharField(max_length=10)),
                ('wheezing', models.CharField(max_length=10)),
                ('alcohol_consuming', models.CharField(max_length=10)),
                ('coughing', models.CharField(max_length=10)),
                ('sob', models.CharField(max_length=10)),
                ('swalling_difficulty', models.CharField(max_length=10)),
                ('chest_pain', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SavePerkinsonEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fo', models.CharField(max_length=10)),
                ('Fhi', models.CharField(max_length=10)),
                ('Flo', models.CharField(max_length=10)),
                ('Jitter_p', models.CharField(max_length=10)),
                ('Jitter_a', models.CharField(max_length=10)),
                ('RAP', models.CharField(max_length=10)),
                ('PPQ', models.CharField(max_length=10)),
                ('DDP', models.CharField(max_length=10)),
                ('Shimmer', models.CharField(max_length=10)),
                ('Shimmer_db', models.CharField(max_length=10)),
                ('APQ3', models.CharField(max_length=10)),
                ('APQ5', models.CharField(max_length=10)),
                ('APQ', models.CharField(max_length=10)),
                ('DDA', models.CharField(max_length=10)),
                ('NHR', models.CharField(max_length=10)),
                ('HNR', models.CharField(max_length=10)),
                ('RPDE', models.CharField(max_length=10)),
                ('DFA', models.CharField(max_length=10)),
                ('spread1', models.CharField(max_length=10)),
                ('spread2', models.CharField(max_length=10)),
                ('D2', models.CharField(max_length=10)),
                ('PPE', models.CharField(max_length=10)),
            ],
        ),
    ]
