# Generated by Django 4.1.4 on 2023-01-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0003_savelungcancerenquiry_saveperkinsonenquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavePerkinsonEnquiry',
            new_name='SaveParkinsonEnquiry',
        ),
    ]
