# Generated by Django 4.1.4 on 2023-01-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0004_rename_saveperkinsonenquiry_saveparkinsonenquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveparkinsonenquiry',
            old_name='Fhi',
            new_name='fhi',
        ),
        migrations.RenameField(
            model_name='saveparkinsonenquiry',
            old_name='Flo',
            new_name='flo',
        ),
        migrations.RenameField(
            model_name='saveparkinsonenquiry',
            old_name='Fo',
            new_name='fo',
        ),
        migrations.RenameField(
            model_name='saveparkinsonenquiry',
            old_name='Jitter_a',
            new_name='jitter_a',
        ),
        migrations.RenameField(
            model_name='saveparkinsonenquiry',
            old_name='Jitter_p',
            new_name='jitter_p',
        ),
        migrations.RenameField(
            model_name='saveparkinsonenquiry',
            old_name='Shimmer',
            new_name='shimmer',
        ),
        migrations.RenameField(
            model_name='saveparkinsonenquiry',
            old_name='Shimmer_db',
            new_name='shimmer_db',
        ),
    ]
